

CREATE TABLESPACE ts_bvd
    DATAFILE 'C:\Work\lab2\tbls\ts_bvd_pdb.dbf'
    SIZE 7 m
    AUTOEXTEND ON NEXT 5M
    MAXSIZE 20M
    EXTENT MANAGEMENT LOCAL;
    
    
   drop tablespace ts_bvd
    --drop tablespace ts_bvd_temp

CREATE TEMPORARY TABLESPACE  ts_bvd_temp
    TEMPFILE 'C:\Work\lab2\tbls\ts_bvd_temp.dbf'
    SIZE 5 m
    AUTOEXTEND ON NEXT 3M
    MAXSIZE 30M
    EXTENT MANAGEMENT LOCAL;
    
    SELECT FILE_NAME, TABLESPACE_NAME, STATUS, MAXBYTES, USER_BYTES FROM DBA_DATA_FILES
UNION
SELECT FILE_NAME, TABLESPACE_NAME, STATUS, MAXBYTES, USER_BYTES FROM DBA_TEMP_FILES;

ALTER DATABASE OPEN;
CREATE ROLE RL_BVDCORE;

GRANT CREATE SESSION TO RL_BVDCORE;

GRANT 
 CREATE TABLE,
 CREATE PROCEDURE,
 CREATE TRIGGER,
 CREATE VIEW,
 CREATE SEQUENCE
TO RL_BVDCORE;
  
SELECT *FROM DBA_ROLES WHERE ROLE LIKE 'RL%';
  
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'RL_BVDCORE'


--CREATE PROFILE PF_BVDCORE LIMIT 
--   SESSIONS_PER_USER          UNLIMITED 
--   CPU_PER_SESSION            UNLIMITED 
--   CPU_PER_CALL               3000 
--   CONNECT_TIME               45 
--   LOGICAL_READS_PER_SESSION  DEFAULT 
--   LOGICAL_READS_PER_CALL     1000 
--   PRIVATE_SGA                15K
--   COMPOSITE_LIMIT            5000000; 
--  
 DROP PROFILE PF_BVDCORE;
  
  CREATE PROFILE PF_BVDCORE LIMIT
   FAILED_LOGIN_ATTEMPTS 5
   PASSWORD_LIFE_TIME 60
   PASSWORD_REUSE_TIME 60
   PASSWORD_REUSE_MAX 5
   PASSWORD_LOCK_TIME 1/24
   PASSWORD_GRACE_TIME 10;
   
  
   
   

SELECT *FROM DBA_PROFILES WHERE PROFILE = 'PF_BVDCORE'
SELECT *FROM DBA_PROFILES WHERE PROFILE = 'DEFAULT'



  drop user BVDCORE;
  
  CREATE USER BVDCORE IDENTIFIED BY pass
    DEFAULT TABLESPACE ts_bvd 
    TEMPORARY TABLESPACE ts_bvd_temp
    PROFILE PF_BVDCORE
    ACCOUNT UNLOCK
    //--PASSWORD EXPIRE
    
    GRANT CREATE SESSION TO BVDCORE
    
    GRANT CREATE TABLE TO BVDCORE
    
    GRANT CREATE TABLESPACE TO BVDCORE
    
    CREATE TABLE NEWUSERTABLE
( customer_id number(10) NOT NULL,
  customer_name varchar2(50) NOT NULL,
  city varchar2(50)
);

CREATE TABLESPACE bvd_data
    DATAFILE 'C:\Work\lab2\tbls\user\ts_bvd_pdb.dbf'
    SIZE 10 m;